sudo: required

language: go

go:
  - "1.10"
  - "1.11"
  - "1.12"
  - "1.13"
  - tip

services:
  - docker

script:
  - make test

after_success:
  - bash <(curl -s https://codecov.io/bash) -f .cover/coverage.txt
